---
functional:
  - Пользователь должен иметь возможность писать личные сообщения дургим пользвотелям которые находятся как в offline так и online
  - Пользователь должен иметь возможность писать в общий чат
  - Пользователь должен иметь возможность создавать игры с ботом,так и присоединятся в игру с другим пользователем
  - Пользователь должен иметь возможность отслеживать свое место в рейтинге
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
  - Пользователь должен иметь возможность давать обратную связь
  
